apiVersion: apps/v1
kind: Deployment
metadata:
  name: anton-prod-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anton-prod-gke
  template:
    metadata:
      labels:
        app: anton-prod-gke
    spec:
      containers:
        - name: app
          image: camunda/camunda-bpm-platform
          imagePullPolicy: Always