name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secretes.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secretes.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{DOCKER_USER}}/docker-with-github:$(date +%s)
    - name: Push the Docker image
      run: docker push ${{DOCKER_USER}}/docker-with-github:$(date +%s)